name: lightweight_bloc
description: A lightweight implementation of the Bloc pattern
version: 0.0.5+4
homepage: https://github.com/Danopie/lightweight_bloc

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter

flutter:

